### ISSUE TITLE
BUG : All records are fetched even with draft status

### ISSUE THREAD

**Issue by nbehier** [GawainLynch/bolt-extension-rssfeed#17]
With v3.1 all records are fetched even if they have `draft` status.

Waiting for a fix, I update my personal `rss.twig` template to correct that effect with :
```
{% for record in records if record.status == 'published' %}
```

**Comment by GawainLynch** [comment]
Whoops! I am not used to using the new storage layer for front-end data, and the programmer needs to specify the status — unless using `$app['query']->getContent()`.

Anyway, I have tagged 3.1.3, with my thanks and humble apologies.

**Comment by nbehier** [comment]
Thanks a lot for your so quick fix! You're so great !
