### ISSUE TITLE
bolt 2.1 breaks rssfeed extension

### ISSUE THREAD

**Issue by cathelijne** [GawainLynch/bolt-extension-rssfeed#2]
After upgrading to 2.1, rssfeed breaks bolt:

Fatal error: Call to undefined method Bolt\Storage::getContentTypeAssert() in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/rssfeed/Extension.php on line 54
PHP Fatal Error: Bolt Extensions

There is a fatal error in the 'bolt/rssfeed' extension loaded on your Bolt Installation.
Error: Call to undefined method Bolt\Storage::getContentTypeAssert()
File: extensions/vendor/bolt/rssfeed/Extension.php
Line: 54

You will only be able to continue by manually deleting the extension that is installed at:
extensions/vendor/bolt/rssfeed

**Comment by GawainLynch** [comment]
Hey @cathelijne haven't seen you around in a bit! :wave: 

OK, so I am putting on my Stupid Badge here… I fixed this on **February 10** and pushed the tag, but not the commit to master!

Our Satis server updates about once an hour, so if you remove and re-add circa 10:00 CET you should be good to go. Please let me know if not.

**Comment by cathelijne** [comment]
Working beautifully again, yay!
That was probably the easiest fix ever :trophy: 

And as a positive side effect; I've finally gotten around to writing that script that fixes file permissions for non-root users on a shared apache installation, so all is good :sunglasses:
