### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by JeromeBreizhtorm** [GawainLynch/bolt-extension-rssfeed#3]
Hi,

I have the extension configured and working almost fine on a v2.1.8, except that the returned content type is text/plain for my rss/xml feeds. 

I tried to forcetype it through htaccess but with no success, neither by uninstalling all other extensions. Any idea ?

Thanks

**Comment by GawainLynch** [comment]
I am unable to reproduce this here on v2.1.0, but just for good measure I have tidied up the response object creation/handling and tagged v2.1.1.

**Comment by JeromeBreizhtorm** [comment]
Ok, i messed up with my server configuration. Content-type is ok. Sorry for the inconvenience :)
